armybuilder/urls.py
from django.contrib import admin
from django.urls import path
from armybuilder import views, api
from rest_framework import routers
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from rest_framework.authtoken import views as rest_framework_views
from django.contrib.auth.decorators import login_required

router = routers.DefaultRouter()
router.register(r'units', api.UnitViewSet)
router.register(r'abilities', api.AbilityViewSet)
router.register(r'list', api.ArmyListViewSet)

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.Browse.as_view(), name='home'),
    # url(r'^get_auth_token/$', rest_framework_views.obtain_auth_token, name='get_auth_token'),
    url(r'^api/', include(router.urls)),
    # url(r'about/', views.About.as_view(), name='about'),
    url(r'browse/', views.Browse.as_view(), name='browse'),
    url(r'createlist/', login_required(views.CreateList.as_view()), name='createlist'),
    url(r'viewlists/', views.ViewLists.as_view(), name='viewlists'),
    url(r'editlist/', views.EditList.as_view(), name='editlist'),
    url(r'viewlist/', views.ViewList.as_view(), name='viewlist'),
    url(r'resources/', views.Resources.as_view(), name='resources'),
]

asoif/urls.py
from django.contrib import admin
from django.urls import path
from armybuilder import views
from rest_framework import routers
from django.conf.urls import url, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', include('armybuilder.urls')),
    path('admin/', admin.site.urls),
]

armybuilder/models.py
from django.db import models
from armybuilder.enums.enums import FACTIONS, UNIT_TYPES, ATTACK_TYPES
from django.contrib.auth.models import User


class CombatUnitManager(models.Manager):
    use_for_related_fields = True

    def cu(self, **kwargs):
        return self.filter('type__in', UNIT_TYPES[:-1], **kwargs)


class Unit(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, unique=False,
                            default=None)
    title = models.CharField(max_length=200, unique=False,
                             default=None, null=True)
    cost = models.IntegerField(default=0, null=True)
    type = models.CharField(
        max_length=20,
        choices=tuple((unittypes, unittypes)
                      for unittypes in UNIT_TYPES),
        default=None,
    )
    faction = models.CharField(
        max_length=20,
        choices=tuple((faction, faction)
                      for faction in FACTIONS),
        default=None
    )
    speed = models.IntegerField(default=0, null=True)
    defense = models.IntegerField(default=0, null=True)
    morale = models.IntegerField(default=0, null=True)
    attachment = models.BooleanField(default=False)
    commander = models.BooleanField(default=False)
    unique = models.BooleanField(default=False)
    objects = models.Manager()
    cu = CombatUnitManager()


class ArmyList(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, unique=False,
                            default=None)
    cost = models.IntegerField(default=0)

    faction = models.CharField(
        max_length=20,
        choices=tuple((faction, faction)
                      for faction in FACTIONS),
        default=None
    )
    list_commander = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='+')
    units = models.ManyToManyField(Unit, through='ListUnit', through_fields=('armylist', 'unit'))
    owner = models.ForeignKey(User, on_delete=models.PROTECT, null=True, default=None)


class ListUnit(models.Model):
    id = models.AutoField(primary_key=True)
    armylist = models.ForeignKey(ArmyList, on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    attachment = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='+', null=True)


class Ability(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, unique=False,
                            default=None)
    description = models.CharField(max_length=200, unique=False,
                                   default=None)
    attacktype = models.CharField(
        max_length=20,
        choices=tuple((attacktype, attacktype)
                      for attacktype in ATTACK_TYPES),
        default=None, null=True
    )
    hit = models.IntegerField(default=0, null=True)
    high = models.IntegerField(default=0, null=True)
    med = models.IntegerField(default=0, null=True)
    low = models.IntegerField(default=0, null=True)
    units = models.ManyToManyField(Unit)


class Resource(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, unique=False,
                            default=None)
    description = models.CharField(max_length=200, unique=False,
                                   default=None)
    url = models.CharField(
        max_length=50, unique=True,
        default=None, null=True
    )
    image = models.CharField(
        max_length=50, unique=True,
        default=None, null=True
    )

armybuilder/forms.py
from django import forms
from django.forms import ModelChoiceField
from armybuilder.models import ArmyList, Unit, Ability


class CommanderChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return "%s" % (obj.name)


class ArmyListForm(forms.ModelForm):
    class Meta:
        model = ArmyList
        fields = ['name', 'cost', 'faction', 'list_commander']

    def __init__(self, *args, **kwargs):
        super(ArmyListForm, self).__init__(*args, **kwargs)
        self.fields['list_commander'] = CommanderChoiceField(queryset=Unit.objects.filter(commander=True))
        # self.fields['faction'] = ModelChoiceField(queryset=)

        # self.fields['faction'].empty_label = None

    def clean(self):
        cleaned_data = super(ArmyListForm, self).clean()
        list_commander = cleaned_data.get("list_commander")
        faction = cleaned_data.get("faction")
        name = cleaned_data.get("name")
        existingList = None
        try:
            existingList = ArmyList.objects.get(name=name)
        except ArmyList.DoesNotExist:
            pass

        if faction.lower() != 'neutral' and list_commander.faction.lower() != 'neutral' and list_commander.faction.lower() != faction.lower():
            raise forms.ValidationError("Cannot Choose " + faction + " with " + list_commander.faction + " commander")

        if existingList:
            raise forms.ValidationError("A List with this name has already been created " + name )

        return cleaned_data

armybuilder/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .enums.enums import getFactionList, getCostList, getTypeList, CHARISMATIC_FACTION
from armybuilder import forms
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from armybuilder.models import ArmyList, Unit, Ability, ListUnit, Resource
from armybuilder.services import UnitService, ArmyListService


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class About(TemplateView):

    def get(self, request, **kwargs):
        return render(request, 'about.html')

class ViewLists(TemplateView):

    def get(self, request, **kwargs):
        lists = ArmyListService.getArmyLists(request)
        showMyListsChecked = 'checked' if request.GET.get('showMyLists') == 'true' else ''
        showOtherListsChecked = 'checked' if request.GET.get('showOtherLists') == 'true' else ''
        context = {
            'Factions': getFactionList(request.GET.get('faction')),
            'Costs': getCostList(request.GET.get('cost')),
            'Lists': lists,
            'showMyListsChecked': showMyListsChecked,
            'showOtherListsChecked': showOtherListsChecked,
        }

        return render(request, 'viewlists.html', context)


class CreateList(TemplateView):

    def get(self, request, **kwargs):
        username = None
        if request.user.is_authenticated:
            username = request.user.username

        validCommanders = UnitService.getCommandersForFactions()

        context = {
            'form': forms.ArmyListForm(),
            'validCommanders': validCommanders
        }

        for faction in validCommanders:
            context[faction] = validCommanders[faction]

        return render(request, 'createlist.html', context)

    def post(self, request, *args, **kwargs):
        form = forms.ArmyListForm(
            request.POST, initial=request.session.get('form_data'))

        if form.is_valid() and request.user.is_authenticated:
            list = form.save()
            list.owner_id = request.user
            list.save()
            print(list.list_commander.id)
            commanderUnit = Unit.objects.get(id=list.list_commander.id)
            ListUnit.objects.create(unit=commanderUnit, armylist=list, attachment=None)

            return redirect('../editlist/?id=' + str(list.id))

        return render(request, 'createlist.html', {'form': form})


class Browse(TemplateView):
    def get(self, request, **kwargs):
        selectedFaction = request.GET.get('faction')
        selectedType = request.GET.get('type')
        showAttachments = True if request.GET.get('showAttachments') == 'true' else False
        showCommanders = True if request.GET.get('showCommanders') == 'true' else False
        showNonCombatAbilities = True if request.GET.get('showNonCombatAbilities') == 'true' else False

        factionList = getFactionList(selectedFaction)
        typeList = getTypeList(selectedType)

        units = UnitService.getUnits(selectedFaction, selectedType, showAttachments, showCommanders,
                                     showNonCombatAbilities)

        showCommandersChecked = 'checked' if showCommanders else ''
        showAttachmentsChecked = 'checked' if showAttachments else ''
        showNonCombatAbilitiesChecked = 'checked' if showNonCombatAbilities else ''

        context = {'UnitList': units,
                   'Factions': factionList,
                   'Types': typeList,
                   'showAttachmentsChecked': showAttachmentsChecked,
                   'showCommandersChecked': showCommandersChecked,
                   'showNonCombatAbilitiesChecked': showNonCombatAbilitiesChecked}

        return render(request, 'browse.html', context)


class EditList(TemplateView):
    def get(self, request, **kwargs):
        unitList = ArmyListService.getArmyList(request.GET.get('id'))

        username = None
        if request.user.is_authenticated:
            username = request.user.username
        print(username + " " + unitList.owner.username)
        if (unitList.owner.username != username):
            return redirect('../viewlist/?id=' + str(unitList.id))

        hirableUnitList = UnitService.getHirableUnits(unitList)

        context = {
            'unitList': unitList,
            'availableUnitList': hirableUnitList,
        }

        return render(request, 'editlist.html', context)

class Resources(TemplateView):
    def get(self, request, **kwargs):

        resources = Resource.objects.all()
        context = {
            'resources': resources,
        }
        return render(request, 'resources.html', context)

class ViewList(TemplateView):
    def get(self, request, **kwargs):
        unitList = ArmyListService.getArmyList(request.GET.get('id'))
        hirableUnitList = UnitService.getHirableUnits(unitList)

        context = {
            'unitList': unitList,
            'availableUnitList': hirableUnitList,
        }
        return render(request, 'viewlist.html', context)

armybuilder/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="container marketing">
            <div class="row">
                <div class="content-centered col-sm">
                    <div class="col-lg content-centered">
                        <img class="rounded-circle"
                             src="https://scontent-iad3-1.xx.fbcdn.net/v/t31.0-8/10549150_872983986460_8290368708385600063_o.jpg?_nc_cat=105&oh=8c307bb632ccf18f53855007f9b8c144&oe=5C537522"
                             alt="Generic placeholder image" width="140" height="140">
                        <h2>More About me:</h2>
                        <p style="    padding-bottom: 20px;">I have found myself many things in life, but presently I am
                            a software engineer,
                            philosopher, and father.</p>
                        <p><a class="btn btn-secondary" href="https://www.linkedin.com/in/jonathan-olson-6ab6a3b/"
                              role="button">Connect on Linked in »</a></p>
                    </div>
                </div>
                <div class="content-centered col-sm">
                    <div class="col-lg content-centered">
                        <img class="rounded-circle"
                             src="https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-1/p320x320/38451415_10100475878143710_5591134657237221376_n.jpg?_nc_cat=103&oh=893adb8b2044bb9769307b73203054e4&oe=5C4E01B1"
                             alt="Generic placeholder image" width="140" height="140">
                        <h2>j0n0l.s0n</h2>
                        <p style="    padding-bottom: 20px;">Reach out to my on Facebook Messenger for feedback,
                            suggestions, or more
                            information</p>
                        <p><a class="btn btn-secondary" href="https://www.facebook.com/j0n0l.s0n" role="button">Follow
                            on social media»</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /content -->
    </div>
{% endblock %}

armybuilder/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ASOF&I - A Song of Fire & Ice</title>
    <link rel="shortcut icon" href="{% static 'media/images/favicon/favicon.ico' %}"/>
    <meta name="msapplication-TileImage"
          content="../assets/media/images/favicon/mstile-144x144.png">
    <meta name="msapplication-TileColor" content="#ff0000">
</head>
<div fragment="navbar">
    <div class="navbar navbar-expand-lg navbar-dark fixed-top"
         style=" background-color: darkslategray;" role="banner">
        <div class="container">
            <a class="navbar-brand" href="/browse">aSoI&F: Simple List Builder</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExample07">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/browse">Units</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/createlist">Create List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/viewlists">Lists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/resources">Resources</a>
                    </li>
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="/about">About</a>#}
{#                    </li>#}
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="/accounts/logout">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/accounts/login">Log In</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <body>
    <main style="padding-top: 100px;">
        {% block content %}
        {% endblock %}
    </main>
    </body>
</html>

armybuilder/templates/browse.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="wrapper">
            <div class="content" role="main">
                <div class="shelf shelf_5">
                    <h1 class="hdg hdg_1 content-centered">Unit List</h1>
                </div>
                <div class="row">
                    <div class="split content-centered col-sm" role="main">
                        <div class="shelf">
                            <label for="factionPicker">
                                <h2 class="hdg hdg_2">Select Faction:</h2>
                            </label>
                        </div>
                        <select name="factionPicker" id="factionPicker">
                            <option selected disabled hidden>Choose here</option>
                            {% for Faction in Factions %}
                                <tr id="{{ Faction.value }}">
                                    <option
                                            value="{{ Faction.value }}"
                                            text="{{ Faction.value }}"
                                            {{ Faction.isSelected }}
                                    >{{ Faction.value }}
                                    </option>
                                </tr>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="split content-centered col-sm" role="main">
                        <div class="shelf">
                            <label for="typePicker">
                                <h2 class="hdg hdg_2">Select Type:</h2>
                            </label>
                        </div>
                        <select name="typePicker" id="typePicker">
                            <option selected disabled hidden>Choose here</option>
                            {% for Type in Types %}
                                <tr id="{{ Type.value }}">
                                    <option
                                            value="{{ Type.value }}"
                                            text="{{ Type.value }}"
                                            {{ Type.isSelected }}
                                    >{{ Type.value }}
                                    </option>
                                </tr>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="split content-centered col-sm" role="main">
                        <div class="row">
                            <input type="checkbox" class="form-check-input"
                                   id="showAttachments"  {{ showAttachmentsChecked }}>

                            <label class="form-check-label" for="showAttachments">Show Attachments</label>
                        </div>
                        <div class="row">
                            <input type="checkbox" class="form-check-input"
                                   id="showCommanders"  {{ showCommandersChecked }}>
                            <label class="form-check-label" for="showCommanders">Show Commanders</label>
                        </div>
                        <div class="row">
                            <input type="checkbox" class="form-check-input"
                                   id="showNonCombatAbilities"  {{ showNonCombatAbilitiesChecked }}>
                            <label class="form-check-label" for="showNonCombatAbilities">Show Non-Combat Abilities</label>
                        </div>
                        <div class="row">
                            <a href="/browse">Reset Filters</a>
                        </div>
                    </div>
                </div>
                <div class="shelf shelf_1">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Unit Name</th>
                            <th scope="col">Faction</th>
                            <th scope="col">Cost</th>
                            <th scope="col">Type</th>
                            <th scope="col">Defense</th>
                            <th scope="col">Speed</th>
                            <th scope="col">Morale</th>
                            <th scope="col">Abilities</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for Unit in UnitList %}
                            <tr>
                                <td>{{ Unit.display_name }}</td>
                                <td>{{ Unit.faction }}</td>
                                <td>{{ Unit.cost }}</td>
                                <td>{{ Unit.type }}</td>
                                {% if not Unit.type == "Non-Combat Unit" and Unit.attachment == False %}
                                    <td>{{ Unit.defense }}+
                                        <small style="color: blue;">{{ Unit.defense_percent }}</small>
                                    </td>
                                    <td>{{ Unit.speed }}</td>
                                    <td>{{ Unit.morale }}+
                                        <small style="color: blue;">{{ Unit.morale_percent }}</small>
                                    </td>
                                {% else %}
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                {% endif %}
                                <td>
                                    {% if Unit.abilities %}
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th scope="col">Ability Name</th>
                                                {#                                                <th scope="col">Ability Description</th>#}
                                                {% if Unit.attachment != false and Unit.type != 'Non-Combat Unit' %}
                                                    <th scope="col">Type</th>
                                                    <th scope="col">Hit</th>
                                                    <th scope="col">High</th>
                                                    {% if Unit.type != 'Monster' and Unit.name != 'Gregor Clegane' %}
                                                        <th scope="col">Medium</th>
                                                    {% endif %}
                                                    {% if Unit.type != 'Monster' and Unit.type != 'Cavalry' %}
                                                        <th scope="col">Low</th>
                                                    {% endif %}
                                                {% endif %}
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for ability in Unit.abilities %}
                                                <tr>
                                                    <td data-toggle="tooltip"
                                                        data-original-title={{ ability.description }}>{{ ability.name }}</td>
                                                    {#                                                    <td>{{ ability.description }}</td>#}
                                                    {% if Unit.attachment != false and Unit.type != 'Non-Combat Unit' %}
                                                        {% if ability.attacktype %}
                                                            <td scope="col">{{ ability.attacktype }}</td>
                                                            <td scope="col">{{ ability.hit }}+
                                                                <small style="color: blue;">{{ ability.hit_percent }}</small>
                                                            </td>
                                                            <td scope="col">{{ ability.high }}
                                                                <small style="color: blue;">{{ ability.high_avg_hits }}</small>
                                                            </td>
                                                            {% if Unit.type != 'Monster' and Unit.name != 'Gregor Clegane' %}
                                                                <td scope="col">{{ ability.med }}
                                                                    <small style="color: blue;">{{ ability.med_avg_hits }}</small>
                                                                </td>
                                                            {% endif %}
                                                            {% if Unit.type != 'Monster' and Unit.type != 'Cavalry' %}
                                                                <td scope="col">{{ ability.low }}
                                                                    <small style="color: blue;">{{ ability.low_avg_hits }}</small>
                                                                </td>
                                                            {% endif %}
                                                        {% else %}
                                                            <td></td>
                                                            <td></td>
                                                            <td></td>
                                                            {% if Unit.type != 'Monster' and Unit.name != 'Gregor Clegane' %}
                                                                <td></td>
                                                            {% endif %}
                                                            {% if Unit.type != 'Monster' and Unit.type != 'Cavalry' %}
                                                                <td></td>
                                                            {% endif %}
                                                        {% endif %}
                                                    {% endif %}
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        });

        argList = ["showAttachments", "type", "showCommanders", "showNonCombatAbilities", "faction"];

        function preserve(newArg, value){
            var curr_url = new URL(window.location.href);

            var index = argList.indexOf(newArg);
            if (index !== -1) argList.splice(index, 1);
            var args = [];
            for (i = 0; i < argList.length; i++)
            {
                var curr = curr_url.searchParams.get(argList[i]);
                if (curr)
                    args.push(argList[i]+"=" + curr);
            }


            args.push(newArg + "=" + value);
            var redirect_to = "?" + args.join("&");
            window.location.href = redirect_to;
        };
        window.onload = function () {
            $("#factionPicker").change(function () {
                preserve("faction", this.value);
            });
            $("#typePicker").change(function () {
                preserve("type", this.value);
            });

            $("#showAttachments").change(function () {
                var showAttachmentsBox = document.getElementById("showAttachments");
                preserve("showAttachments", showAttachmentsBox.checked);
            });

            $("#showCommanders").change(function () {

                var showCommandersBox = document.getElementById("showCommanders");
                preserve("showCommanders", showCommandersBox.checked);
            });

            $("#showNonCombatAbilities").change(function () {
                var showNonCombatAbilitiesBox = document.getElementById("showNonCombatAbilities");
                preserve("showNonCombatAbilities", showNonCombatAbilitiesBox.checked);
            });
        };
    </script>
{% endblock %}

armybuilder/templates/createlist.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="wrapper">
            <div class="content-centered" role="main">
                <div class="shelf shelf_5">
                    <h1 class="hdg hdg_1">Build a List</h1>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create List</button>
                </form>
            </div>
        </div>
    </div>
    <script>
        $("#id_faction").change(function () {
            var commanderList;
            if(this.value == "stark"){
                commanderList = "{{ stark }}".split(",");
            }else if(this.value == "lannister"){
                commanderList = "{{ lannister }}".split(",");
            }else if(this.value == "neutral"){
                commanderList = "{{ neutral }}".split(",");
            }

            var commanderPicker = document.getElementById("id_list_commander");
            commanderPicker.options.length = 0;

            for (i = 0; i < commanderList.length; i++) {
                commanderPicker.options[i] = new Option(commanderList[i].split("-")[1], commanderList[i].split("-")[0], true, false)
            }

        });
        $("#id_faction").focus(function () {
            this.selectedIndex = -1;
        });
    </script>
{% endblock %}